RFO.Website/Areas/Admin/Controllers/MenuManagementController.cs
using System;
using System.Dynamic;
using System.Web.Mvc;
using RFO.AspNet.Utilities.Attribute;
using RFO.AspNet.Utilities.ActionResultBuilder;
using RFO.Common.Utilities.Logging;

namespace RFO.Website.Areas.Admin.Controllers
{
    /// <summary>
    /// The controller takes responsibility to handle requests regardless Menu management
    /// </summary>
    public class MenuManagementController : AbstractAdminController
    {
        #region Override of AbstractAdminController
        
        /// <summary>
        /// Gets the detail view template.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        protected override string GetDetailViewTemplate(int id)
        {
            return this.RenderPartialViewToString("~/Areas/Admin/Views/MenuManagement/_PartialDetail.cshtml", id);
        }

        /// <summary>
        /// Gets the records view template.
        /// </summary>
        /// <returns></returns>
        protected override string GetRecordsViewTemplate()
        {
            dynamic viewModel = new ExpandoObject();
            return this.RenderPartialViewToString("~/Areas/Admin/Views/MenuManagement/_PartialList.cshtml", viewModel);
        }

        #endregion
        
    }
}

RFO.Website/Areas/Admin/Controllers/OrderManagementController.cs
using System;
using System.Dynamic;
using System.Web.Mvc;
using RFO.AspNet.Utilities.Attribute;
using RFO.AspNet.Utilities.ActionResultBuilder;
using RFO.Common.Utilities.Logging;

namespace RFO.Website.Areas.Admin.Controllers
{
    /// <summary>
    /// The controller takes responsibility to handle requests regardless Order management
    /// </summary>
    public class OrderManagementController : AbstractAdminController
    {
        #region Override of AbstractAdminController
        
        /// <summary>
        /// Gets the detail view template.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        protected override string GetDetailViewTemplate(int id)
        {
            return this.RenderPartialViewToString("~/Areas/Admin/Views/OrderManagement/_PartialDetail.cshtml", id);
        }

        /// <summary>
        /// Gets the records view template.
        /// </summary>
        /// <returns></returns>
        protected override string GetRecordsViewTemplate()
        {
            dynamic viewModel = new ExpandoObject();
            return this.RenderPartialViewToString("~/Areas/Admin/Views/OrderManagement/_PartialList.cshtml", viewModel);
        }

        #endregion
        
    }
}

RFO.Website/Areas/Admin/Controllers/TableManagementController.cs
using System;
using System.Dynamic;
using System.Web.Mvc;
using RFO.AspNet.Utilities.Attribute;
using RFO.AspNet.Utilities.ActionResultBuilder;
using RFO.Common.Utilities.Logging;

namespace RFO.Website.Areas.Admin.Controllers
{
    /// <summary>
    /// The controller takes responsibility to handle requests regardless Table management
    /// </summary>
    public class TableManagementController : AbstractAdminController
    {
        #region Override of AbstractAdminController
        
        /// <summary>
        /// Gets the detail view template.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        protected override string GetDetailViewTemplate(int id)
        {
            return this.RenderPartialViewToString("~/Areas/Admin/Views/TableManagement/_PartialDetail.cshtml", id);
        }

        /// <summary>
        /// Gets the records view template.
        /// </summary>
        /// <returns></returns>
        protected override string GetRecordsViewTemplate()
        {
            dynamic viewModel = new ExpandoObject();
            return this.RenderPartialViewToString("~/Areas/Admin/Views/TableManagement/_PartialList.cshtml", viewModel);
        }

        #endregion
        
    }
}

RFO.Website/Areas/Admin/Controllers/UserManagementController.cs
using System;
using System.Dynamic;
using System.Web.Mvc;
using RFO.AspNet.Utilities.Attribute;
using RFO.AspNet.Utilities.ActionResultBuilder;
using RFO.Common.Utilities.Logging;

namespace RFO.Website.Areas.Admin.Controllers
{
    /// <summary>
    /// The controller takes responsibility to handle requests regardless User management
    /// </summary>
    public class UserManagementController : AbstractAdminController
    {
        #region Override of AbstractAdminController
        
        /// <summary>
        /// Gets the detail view template.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        protected override string GetDetailViewTemplate(int id)
        {
            return this.RenderPartialViewToString("~/Areas/Admin/Views/UserManagement/_PartialDetail.cshtml", id);
        }

        /// <summary>
        /// Gets the records view template.
        /// </summary>
        /// <returns></returns>
        protected override string GetRecordsViewTemplate()
        {
            dynamic viewModel = new ExpandoObject();
            return this.RenderPartialViewToString("~/Areas/Admin/Views/UserManagement/_PartialList.cshtml", viewModel);
        }

        #endregion
        
    }
}

RFO.Website/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <center>
            @RenderBody()
        </center>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RFO.Website/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@using System.Web.UI.WebControls
@using RFO.MetaData

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@AppConstants.AppName - @ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800&amp;amp;subset=latin,latin-ext' rel='stylesheet' type='text/css' id="googlefont">
    <script type="text/javascript">
        var CKEDITOR_BASEPATH = "@Url.Content("~/Templates/Admin/js/plugins/ckeditor/")";
    </script>
    @Styles.Render("~/bundles/fonts")
    @Styles.Render("~/bundles/admincss")
    @Scripts.Render("~/bundles/adminjs")
</head>
<body>
    <div id="navigation">
        <div class="container-fluid">
            <a href="@Url.Action("Index", "Home", new { area = ""})"><img src="~/Templates/Admin/images/logo.jpg" width="50dp" height="50dp" /></a>
            <a href="@Url.Action("Index", "TableOrderManagement")">
                <font color="#ffffff" size="5">
                    @AppConstants.AppName
                </font>
            </a>
            <a href="#" class="toggle-nav" rel="tooltip" data-placement="bottom" title=""><i class="icon-reorder"></i></a>
            <div class="user">
                <ul class="icon-nav">
                    <li class="dropdown sett">
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-cog"></i></a>
                        <ul class="dropdown-menu pull-right theme-settings">
                            <li>
                                <span>Layout-width</span>
                                <div class="version-toggle">
                                    <a href="#" class='set-fixed'>Fixed</a>
                                    <a href="#" class="active set-fluid">Fluid</a>
                                </div>
                            </li>
                            <li>
                                <span>Topbar</span>
                                <div class="topbar-toggle">
                                    <a href="#" class='set-topbar-fixed'>Fixed</a>
                                    <a href="#" class="active set-topbar-default">Default</a>
                                </div>
                            </li>
                            <li>
                                <span>Sidebar</span>
                                <div class="sidebar-toggle">
                                    <a href="#" class='set-sidebar-fixed'>Fixed</a>
                                    <a href="#" class="active set-sidebar-default">Default</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class='dropdown colo'>
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown"><i class="icon-tint"></i></a>
                        <ul class="dropdown-menu pull-right theme-colors">
                            <li class="subtitle">
                                Predefined colors
                            </li>
                            <li>
                                <span class='red'></span>
                                <span class='orange'></span>
                                <span class='green'></span>
                                <span class="brown"></span>
                                <span class="blue"></span>
                                <span class='lime'></span>
                                <span class="teal"></span>
                                <span class="purple"></span>
                                <span class="pink"></span>
                                <span class="magenta"></span>
                                <span class="grey"></span>
                                <span class="darkblue"></span>
                                <span class="lightred"></span>
                                <span class="lightgrey"></span>
                                <span class="satblue"></span>
                                <span class="satgreen"></span>
                            </li>
                        </ul>
                    </li>
                </ul>
                @*<div class="dropdown">
                    <a href="#" class='dropdown-toggle' data-toggle="dropdown">
                        @currentUserName
                        <img id="UserAvatarFile" alt="">
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a onclick="@selectDetailUrlFunc">Chỉnh sửa tài khoản</a>
                        </li>
                        <li>
                            <a onclick="@changePasswordUrlFunc">Đổi mật khẩu</a>
                        </li>
                        <li>
                            @Html.ActionLink("Đăng xuất", "LogOff", "Account", new { Area = "" }, null)
                        </li>
                    </ul>
                </div>*@
            </div>
        </div>
    </div>
    <div class="container-fluid" id="content">
        <div id="left">
            <!--Partial detail template-->
            @Html.Partial("_PartialSidebar")
        </div>
        <div id="main">
            @*<div class="container-fluid">
                <div class="page-header">
                    @*<div class="pull-right">
                        <ul class="stats">
                        </ul>
                    </div>
                </div>
            </div>*@
            <!--Render to other pages-->
            @RenderBody()
            
            <!--Partial detail template-->
            @Html.Partial("~/Areas/Admin/Views/Shared/_PartialBoxTemplate.cshtml")
        </div>
        
    </div>
</body>

</html>

RFO.Website/Areas/Admin/Views/Shared/_PartialBoxTemplate.cshtml
<!-- Box dialog template -->
<div id="admin-box-dlg" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-body" style="padding: 0px">
        <div class="container-fluid" style="padding-bottom: 20px;">
            <div class="row-fluid">
                <div class="span12">
                    <div class="box box-bordered box-color">
                        <div class="box-title">
                            <h3>
                                <i class="icon-edit"></i>
                                <span id="admin-box-title">Thông tin chi tiết</span>
                            </h3>
                            <a href="#" class="box-dlg-close" data-dismiss="modal" aria-hidden="true">Close</a>
                        </div>
                        <div id="admin-box-body" class="box-content nopadding">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

RFO.Website/Areas/Admin/Views/Shared/_PartialSidebar.cshtml
@using RFO.Common.Utilities.Localization
@{
    var translationManager = (ITranslationManager)this.Session["TranslationManager"];
}

<div class="subnav">
        <div class="subnav-title">
            <a href="#" class='toggle-subnav'>
                @*<i class="icon-angle-down"></i>*@
                <span>Restaurant</span>
            </a>
        </div>
        <ul class="subnav-menu">
                    <li>
                        <a href="@Url.Action("Index", "TableManagement")">Table</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "MenuManagement")">Status</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "ProductManagement")">Menu</a>
                    </li>
        </ul>
    </div>
    <div class="subnav">
        <div class="subnav-title">
            <a href="#" class='toggle-subnav'>    
                @*<i class="icon-angle-down" ></i>*@          
                <span>Order</span>
                
            </a>
        </div>
        <ul class="subnav-menu">
            <li>
                <a href="@Url.Action("Index", "OrderStateManagement")">Order State</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "TableOrderManagement")">Table Order</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "OrderManagement")">Bill</a>
            </li>
        </ul>
    </div>
    <div class="subnav">
        <div class="subnav-title">
            <a href="@Url.Action("Index", "UserManagement")" class='subnav-normal'>
                <span>Staff</span>
            </a>
        </div>
    </div>
    @*<div class="subnav">
        <div class="subnav-title">
            <a href="@Url.Action("Index", "PromotionManagement")" class='subnav-normal'>
                <span>Promotion</span>
            </a>
        </div>
    </div>*@